# Generated by Django 3.2.5 on 2021-07-22 13:11

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestingRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('file', models.FileField(upload_to='media/')),
                ('code0', models.TextField(blank=True, default='', max_length=2000)),
                ('code1', models.TextField(blank=True, default='', max_length=2000)),
                ('code2', models.TextField(blank=True, default='', max_length=2000)),
                ('code4', models.TextField(blank=True, default='', max_length=2000)),
                ('code5', models.TextField(blank=True, default='', max_length=2000)),
            ],
        ),
    ]
