# Generated by Django 3.2.5 on 2021-07-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingrecording',
            name='dists',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
