# Generated by Django 3.2.5 on 2021-07-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnosis', '0003_alter_testingrecording_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingrecording',
            name='title',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
