# Generated by Django 3.2.5 on 2021-07-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnosis', '0004_testingrecording_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingrecording',
            name='n_targets',
            field=models.IntegerField(default=1),
        ),
    ]
