# Generated by Django 3.2.5 on 2021-07-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnosis', '0005_testingrecording_n_targets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', max_length=500)),
                ('num_targets', models.IntegerField(default=1)),
                ('dist1', models.FloatField(default=0)),
                ('dist2', models.FloatField(default=0)),
                ('vel1', models.FloatField(default=0)),
                ('vel2', models.FloatField(default=0)),
                ('vel_our', models.FloatField(default=0)),
                ('course1', models.FloatField(default=0)),
                ('course2', models.FloatField(default=0)),
            ],
        ),
    ]
