# Generated by Django 3.2.5 on 2021-07-26 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnosis', '0006_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenariosSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_targets', models.IntegerField(default=1)),
                ('n_cases', models.IntegerField(default=0)),
                ('metafile', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='scenariosSet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='diagnosis.scenariosset'),
        ),
    ]
