# Generated by Django 3.2.5 on 2021-07-27 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnosis', '0007_auto_20210726_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingrecording',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ScenarioResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(
                    choices=[(0, 'OK'), (1, 'Ok with violations'), (2, 'Not solved'), (3, 'Refuse: too many targets'),
                             (4, 'Undefined scenario for dangerous target'), (5, 'No dangerous vehicles')], default=0)),
                ('exec_time', models.FloatField(default=0)),
                ('nav_report', models.TextField(default='', max_length=3000)),
                ('command', models.TextField(default='', max_length=3000)),
                ('dist1', models.FloatField(default=0)),
                ('dist2', models.FloatField(default=0)),
                ('course1', models.FloatField(default=0)),
                ('course2', models.FloatField(default=0)),
                ('peleng1', models.FloatField(default=0)),
                ('peleng2', models.FloatField(default=0)),
                ('type1', models.TextField(default='', max_length=300)),
                ('type2', models.TextField(default='', max_length=300)),
                ('pack',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.testingrecording')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.scenario')),
            ],
        ),
    ]
