# Generated by Django 3.2.5 on 2021-07-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnosis', '0008_auto_20210727_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='peleng1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scenario',
            name='peleng2',
            field=models.FloatField(default=0),
        ),
    ]
